const RECIPES = [
  {
    title: "Steel Cut Oats",
    meal: "Breakfast Staples",
    time: 25,
    rating: 8,
  },
  {
    title: "Thick Cut Avocado Toast",
    meal: "Breakfast Staples",
    time: 15,
    rating: 10,
  },
  {
    title: "Biscuits",
    meal: "Breakfast Staples",
    time: 60,
    rating: 10,
  },
  {
    title: "Yogurt Dip",
    meal: "Lunctime Favorites",
    time: 8,
    rating: 7,
  },
  {
    title: "Tuna Salad Sandwiches",
    meal: "Lunchtime Favorites",
    time: 30,
    rating: 10,
  },
  {
    title: "Baked Yam with Buffalo Sauce",
    meal: "Lunchtime Favorites",
    time: 60,
    rating: 9,
  },
  {
    title: "Vegetarian Chili",
    meal: "Dinner Mains",
    time: 90,
    rating: 10,
  },
  {
    title: "One Pan Fish",
    meal: "Dinner Mains",
    time: 40,
    rating: 9,
  },
  {
    title: "Baked Tofu in Cream of Mushroom Sauce",
    meal: "Dinner Mains",
    time: 50,
    rating: 10,
  },
  {
    title: "Brussel Sprout Hash",
    meal: "Sides",
    time: 40,
    rating: 8,
  },
  {
    title: "Charred Broccoli",
    meal: "Sides",
    time: 40,
    rating: 9,
  },
  {
    title: "Yammy Mashed Potatoes",
    meal: "Sides",
    time: 69,
    rating: 10,
  },
  {
    title: "Chocolate Roll Cake with Chocolate Ganache",
    meal: "Desserts",
    time: 90,
    rating: 10,
  },
  {
    title: "Oatmeal Chocolate Chip Cookies",
    meal: "Desserts",
    time: 60,
    rating: 9,
  },
  {
    title: "Chocolate Haupia Pie",
    meal: "Desserts",
    time: 360,
    rating: 10,
  },
  {
    title: "Classic Mojito",
    meal: "Cocktails",
    time: 10,
    rating: 10,
  },
  {
    title: "Irish Coffee",
    meal: "Cocktails",
    time: 20,
    rating: 10,
  },
  {
    title: "Classic Pisco Sour",
    meal: "Cocktails",
    time: 10,
    rating: 8,
  },
];
